/**
 * Donor presets — defines terminology, methodology boilerplate, and
 * mandatory disclosure language for GIZ, USAID, EU, and generic reports.
 */

export type DonorPresetId = 'generic' | 'giz' | 'usaid' | 'eu';

export interface DonorPreset {
  id: DonorPresetId;
  label: string;
  coverFooterText: string;
  ssiLabel: string;
  fgdLabel: string;
  methodologyNote: string;
  evidenceScale: {
    strong: string;
    moderate: string;
    weak: string;
    notFound: string;
  };
  mandatoryAnnex?: string;
}

export const DONOR_PRESETS: Record<DonorPresetId, DonorPreset> = {
  generic: {
    id: 'generic',
    label: 'Generic',
    coverFooterText: 'Generated by Athar أثر · athar.ai · Zero data retention policy',
    ssiLabel: 'Semi-Structured Interview (SSI)',
    fgdLabel: 'Focus Group Discussion (FGD)',
    methodologyNote:
      'This analysis applies systematic qualitative coding to primary data collected through semi-structured interviews and/or focus group discussions. Themes were identified inductively and validated through iterative review. The analysis follows recognized qualitative research standards including member-checking and reflexive coding procedures.',
    evidenceScale: {
      strong: 'Strong',
      moderate: 'Moderate',
      weak: 'Weak',
      notFound: 'Not found',
    },
  },

  giz: {
    id: 'giz',
    label: 'GIZ',
    coverFooterText:
      'Implemented with support of Deutsche Gesellschaft für Internationale Zusammenarbeit (GIZ) GmbH',
    ssiLabel: 'Key Informant Interview (KII)',
    fgdLabel: 'Focus Group Discussion (FGD)',
    methodologyNote:
      'This analysis applies thematic coding in line with GIZ quality standards for evaluative studies, based on OECD-DAC evaluation criteria. Findings are presented per the GIZ annotated report structure for qualitative annexes. The evaluation team ensured triangulation across data sources, impartial analysis, and compliance with GIZ data protection requirements throughout the analytical process.',
    evidenceScale: {
      strong: 'Strongly substantiated',
      moderate: 'Substantiated',
      weak: 'Partially substantiated',
      notFound: 'Insufficient evidence',
    },
    mandatoryAnnex:
      'This annex was produced as part of GIZ\'s knowledge management system. Findings will be fed into the relevant sector topic cluster. This document is intended for internal knowledge management purposes and should be reviewed by the responsible GIZ project manager before external dissemination.',
  },

  usaid: {
    id: 'usaid',
    label: 'USAID',
    coverFooterText:
      'This report was produced under a USAID-funded activity. The contents are the responsibility of the implementing partner and do not necessarily reflect the views of USAID or the United States Government.',
    ssiLabel: 'Key Informant Interview (KII)',
    fgdLabel: 'Focus Group Discussion (FGD)',
    methodologyNote:
      'Data collection and analysis comply with USAID ADS 201 evaluation standards. Findings, conclusions, and recommendations are based on evidence derived from primary qualitative data. Data collection tools are available as an annex per ADS 201maa requirements. Gender disaggregation was applied where data permitted. The evaluation team maintained independence and impartiality throughout the analytical process in accordance with USAID evaluation quality standards.',
    evidenceScale: {
      strong: 'High confidence',
      moderate: 'Moderate confidence',
      weak: 'Low confidence',
      notFound: 'Insufficient data',
    },
    mandatoryAnnex:
      'Disclosure: No conflicts of interest were identified among the analysis team. This analysis is consistent with USAID\'s evaluation transparency policy. The implementing partner certifies that this analysis meets the quality standards established under ADS 201 and the relevant Performance Monitoring and Evaluation Plan (PMEP).',
  },

  eu: {
    id: 'eu',
    label: 'European Union',
    coverFooterText:
      'This document has been produced with the financial assistance of the European Union. The contents of this document are the sole responsibility of [Organization] and can in no way be taken to reflect the views of the European Union.',
    ssiLabel: 'Key Informant Interview (KII)',
    fgdLabel: 'Focus Group Discussion (FGD)',
    methodologyNote:
      'This qualitative analysis follows the EU Logical Framework Approach (LFA) reporting structure. Findings are presented at Output, Outcome, and Overall Objective levels consistent with the EC PRAG Logframe Matrix. Indicators are referenced using Objectively Verifiable Indicators (OVIs) and Means of Verification (MoVs) from the project logframe. The analysis team applied OECD-DAC evaluation criteria (Relevance, Effectiveness, Efficiency, Impact, Sustainability) where applicable to the qualitative evidence base.',
    evidenceScale: {
      strong: 'Achievement confirmed',
      moderate: 'Achievement likely',
      weak: 'Achievement uncertain',
      notFound: 'No evidence available',
    },
    mandatoryAnnex:
      'Results are reported in alignment with the EU Results Framework. Where applicable, core indicators are flagged for aggregation reporting to DG INTPA. This analysis contributes to the annual monitoring reporting cycle and should be submitted to the EU Delegation as an annex to the progress report.',
  },
};

export function getDonorPreset(id: DonorPresetId): DonorPreset {
  return DONOR_PRESETS[id] ?? DONOR_PRESETS.generic;
}
