export type DonorPresetId = 'generic' | 'giz' | 'usaid' | 'eu'

export interface DonorPreset {
  id: DonorPresetId
  label: string
  ssiLabel: string
  fgdLabel: string
  coverFooterText: string
  methodologyNote: string
  evidenceScale: {
    strong: string
    moderate: string
    weak: string
    notFound: string
  }
  mandatoryAnnexTitle?: string
  mandatoryAnnexBody?: string
  reportingLevels?: string[]
}

const GENERIC_PRESET: DonorPreset = {
  id: 'generic',
  label: 'Generic (No donor format)',
  ssiLabel: 'Semi-Structured Interview (SSI)',
  fgdLabel: 'Focus Group Discussion (FGD)',
  coverFooterText: 'Generated by Athar أثر · athar.ai',
  methodologyNote: 'Qualitative data was collected through primary field research and analyzed using [methodology]. Themes were identified inductively from transcript data. Supporting quotes are presented verbatim where possible.',
  evidenceScale: {
    strong: 'Strong',
    moderate: 'Moderate',
    weak: 'Weak',
    notFound: 'Not found'
  }
}

const GIZ_PRESET: DonorPreset = {
  id: 'giz',
  label: 'GIZ (Deutsche Gesellschaft für Internationale Zusammenarbeit)',
  ssiLabel: 'Key Informant Interview (KII)',
  fgdLabel: 'Focus Group Discussion (FGD)',
  coverFooterText: 'Implemented with support of Deutsche Gesellschaft für Internationale Zusammenarbeit (GIZ) GmbH on behalf of the German Federal Ministry for Economic Cooperation and Development (BMZ)',
  methodologyNote: 'This qualitative analysis applies thematic coding consistent with GIZ quality standards for evaluative studies. Analysis is framed using OECD-DAC evaluation criteria (relevance, coherence, effectiveness, efficiency, impact, sustainability). Findings are presented per GIZ annotated report structure requirements for qualitative annexes. Quality assurance was applied throughout the analysis process in line with DeGEval Standards für Evaluation.',
  evidenceScale: {
    strong: 'Strongly substantiated — multiple convergent sources',
    moderate: 'Substantiated — consistent evidence with minor gaps',
    weak: 'Partially substantiated — limited or single-source evidence',
    notFound: 'Insufficient evidence — further data collection recommended'
  },
  mandatoryAnnexTitle: 'Knowledge Management Note',
  mandatoryAnnexBody: 'In line with GIZ knowledge management policy, findings from this analysis will be fed into the relevant sector topic cluster to support organisational learning. Evaluation findings are subject to a reflection and dialogue process with project stakeholders prior to final dissemination. This document should be reviewed by the responsible GIZ Corporate Unit Evaluation representative before external publication.'
}

const USAID_PRESET: DonorPreset = {
  id: 'usaid',
  label: 'USAID (United States Agency for International Development)',
  ssiLabel: 'Key Informant Interview (KII)',
  fgdLabel: 'Focus Group Discussion (FGD)',
  coverFooterText: 'This report was produced under a USAID-funded activity. The contents are the responsibility of the implementing organization and do not necessarily reflect the views of USAID or the United States Government. USAID Branding and Marking requirements apply to this document.',
  methodologyNote: 'Data collection and analysis were conducted in compliance with USAID ADS 201 evaluation standards and Annex 201maa quality criteria. Findings, conclusions, and recommendations are based on evidence derived from the best methods available given evaluation questions and available resources. Gender disaggregation was applied to data collection and analysis where sample size permitted. Data collection instruments are available in the annex per ADS 201 requirements.',
  evidenceScale: {
    strong: 'High confidence — multiple independent sources confirm finding',
    moderate: 'Moderate confidence — finding supported with minor uncertainty',
    weak: 'Low confidence — limited evidence, finding requires validation',
    notFound: 'Insufficient data — no evidence available for this indicator'
  },
  mandatoryAnnexTitle: 'Conflicts of Interest Disclosure',
  mandatoryAnnexBody: 'In compliance with USAID ADS 201 and the Evidence-Based Policymaking Act (2019), all members of the analysis team confirm no real or potential conflicts of interest that could influence objectivity or independence of this analysis.'
}

const EU_PRESET: DonorPreset = {
  id: 'eu',
  label: 'European Union (DG INTPA / EuropeAid)',
  ssiLabel: 'Key Informant Interview (KII)',
  fgdLabel: 'Focus Group Discussion (FGD)',
  coverFooterText: 'This document has been produced with the financial assistance of the European Union. The contents of this document are the sole responsibility of [Organization] and can in no way be taken to reflect the views of the European Union.',
  methodologyNote: 'This qualitative analysis follows the EU Logical Framework Approach (LFA) reporting structure as defined in the European Commission PRAG guidelines. Findings are presented at three result levels: Outputs (direct deliverables), Outcomes/Specific Objectives (benefits to target groups), and Overall Objective (broader development impact). Indicators reference Objectively Verifiable Indicators (OVIs) with corresponding Means of Verification (MoVs). Where applicable, findings are cross-referenced with EU Results Framework (EURF) core indicators for DG INTPA corporate reporting purposes.',
  evidenceScale: {
    strong: 'Achievement confirmed — strong verifiable evidence',
    moderate: 'Achievement likely — evidence supports positive trajectory',
    weak: 'Achievement uncertain — insufficient or contradictory evidence',
    notFound: 'No evidence available — MoV not reached or data gap identified'
  },
  reportingLevels: ['Output', 'Outcome / Specific Objective', 'Overall Objective'],
  mandatoryAnnexTitle: 'EU Results Framework Alignment',
  mandatoryAnnexBody: 'Results reported in this analysis are aligned with the EU Results Framework where applicable. Core indicators subject to aggregation reporting to DG INTPA are flagged in the Logframe Alignment section. This document is subject to quality review by the Operational Manager prior to submission to the European Commission.'
}

export const DONOR_PRESETS: Record<DonorPresetId, DonorPreset> = {
  generic: GENERIC_PRESET,
  giz: GIZ_PRESET,
  usaid: USAID_PRESET,
  eu: EU_PRESET,
}

export function getDonorPreset(id: DonorPresetId): DonorPreset {
  return DONOR_PRESETS[id] ?? DONOR_PRESETS.generic
}
