export const AR_LABELS = {
  codingMatrix:       'مصفوفة الترميز',
  frequencySummary:   'ملخص التكرار',
  logframeAlignment:  'التوافق مع الإطار المنطقي',
  metadata:           'البيانات الوصفية',
  themeId:            'رقم المحور',
  themeName:          'المحور',
  subTheme:           'المحور الفرعي',
  quote:              'الاقتباس',
  frequency:          'التكرار',
  source:             'المصدر',
  logframeIndicator:  'مؤشر الإطار المنطقي',
  evidenceStrength:   'قوة الدليل',
  strong:             'قوي',
  moderate:           'متوسط',
  weak:               'ضعيف',
  notFound:           'غير موجود',
  executiveSummary:   'الملخص التنفيذي',
  methodology:        'المنهجية',
  keyFindings:        'النتائج الرئيسية',
  themes:             'المحاور',
  recommendations:    'التوصيات',
  gaps:               'الفجوات والقيود',
  annexes:            'الملاحق',
  generatedBy:        'أُنتج بواسطة أثر',
  retentionNote:      'تمت معالجة الملفات في الذاكرة فقط. لم يتم تخزين أي بيانات.',
  topThemes:          'أبرز المحاور',
  keyFinding:         'نتيجة رئيسية',
  quoteHighlight:     'اقتباس بارز',
  analysisBy:         'تحليل بواسطة أثر',
  qualitativeSummary: 'ملخص التحليل النوعي',
  wordsAnalyzed:      'عدد الكلمات المحللة',
  nothingStored:      'لم يتم تخزين أي شيء · athar.ai',
  filesProcessed:     'تمت معالجة الملفات في الذاكرة فقط.',
}
